// src/components/special/MySkills/MySkills.svelte
<script lang="ts">
  import IconFolderSrcOpen from '../../../assets/icons/folder-src-open.svg?component';
  import { SKILL_CATEGORIES, SKILLS } from '../../../config/skills';
  import SkillsExplorer, { SkillItem, SkillsFolder } from '../SkillsExplorer';
</script>

<SkillsExplorer class={$$restProps.class}>
  <SkillsFolder icon={IconFolderSrcOpen}>
    <svelte:fragment slot="name">My Skills</svelte:fragment>
    <svelte:fragment slot="hint">(click them)</svelte:fragment>
    <svelte:fragment>
      {#each SKILL_CATEGORIES as category (category.id)}
        <SkillsFolder icon={category.icon} expandable>
          <svelte:fragment slot="name">{category.name}</svelte:fragment>
          <svelte:fragment>
            {#each SKILLS.filter((s) => s.categoryId === category.id) as skill (skill.id)}
              <SkillItem icon={skill.icon}>
                <svelte:fragment slot="hint">
                  {skill.hint || ''}
                </svelte:fragment>
                <svelte:fragment>{skill.name}</svelte:fragment>
              </SkillItem>
            {/each}
          </svelte:fragment>
        </SkillsFolder>
      {/each}
    </svelte:fragment>
  </SkillsFolder>
</SkillsExplorer>

// src/routes/IndexRoute/MySkills/MySkills.tsx
import React from "react";

import { ReactComponent as FolderSrcIcon } from "~/assets/icons/folder-src-open.svg";

import { SkillsExplorer, SkillsFolder } from "~/components/SkillsExplorer";
import { SKILL_CATEGORIES, Skill } from "~/config/skills";

import { MySkillCategory } from "./MySkillCategory";

export interface MySkillsProps {
  className?: string;
  onSkillClick: (skill: Skill) => void;
}

export const MySkillsBase: React.FC<MySkillsProps> = (props) => {
  return (
    <SkillsExplorer className={props.className}>
      <SkillsFolder icon={FolderSrcIcon} name="My Skills" expandable={false}>
        {SKILL_CATEGORIES.map((category) => (
          <MySkillCategory
            key={category.id}
            {...category}
            onSkillClick={props.onSkillClick}
          />
        ))}
      </SkillsFolder>
    </SkillsExplorer>
  );
};

export const MySkillsContainer: React.FC = () => {
  return <MySkillsBase onSkillClick={(skill) => console.log("skill", skill)} />;
};

export const MySkills = React.memo(MySkillsContainer);
