// src/routes/IndexRoute/Navigation/Navigation.tsx
import React from "react";
import clsx from "clsx";

import { ROUTES_META } from "~/config/routesMeta";

import { useStyles } from "./Navigation.styles";
import { NavLink } from "./NavLink";

interface NavigationProps {
  className?: string;
}

const NavigationBase: React.FC<NavigationProps> = (props) => {
  const classes = useStyles();
  return (
    <div className={clsx(classes.navigation, props.className)}>
      {Object.values(ROUTES_META).map((route) => (
        <NavLink
          key={route.to}
          to={route.to}
          icon={route.icon}
          activeOnlyWhenExact={route.activeOnlyWhenExact}
        >
          {route.label}
        </NavLink>
      ))}
    </div>
  );
};

export const Navigation = React.memo(NavigationBase);

// src/components/layout/Navigation/Navigation.svelte
<script lang="ts">
  import { clsx } from 'clsx';

  import { ROUTES_META } from '../../../config/routesMeta';
  import NavLink from '../../common/NavLink';

  import styles from './Navigation.module.scss';

  let routes = Object.values(ROUTES_META).filter((r) => !r.hidden);
</script>

<div class={clsx(styles.navigation, $$restProps.class)}>
  {#each routes as route (route.to)}
    <NavLink
      activeOnlyWhenExact={route.activeOnlyWhenExact}
      activeClass={styles.active}
      class={styles.navLink}
      hasIcon
      icon={route.icon}
      to={route.to}
    >
      {route.label}
    </NavLink>
  {/each}
</div>
