// src/components/layout/Breadcrumbs/Breadcrumbs.svelte
<script lang="ts">
  import IconChevronRight from 'svelte-material-icons/ChevronRight.svelte';
  import { Link, useLocation } from 'svelte-routing';

  import IconJson from '../../../assets/icons/json.svg?component';
  import { ROUTES_META } from '../../../config/routesMeta';
  import Popup from '../../common/Popup';

  import styles from './Breadcrumbs.module.scss';

  let isMenuOpened = false;

  const location = useLocation();

  $: currentRoute = ROUTES_META[$location.pathname];
  $: routeIcon = currentRoute.icon || IconJson;
  $: restRoutes = Object.values(ROUTES_META).filter((r) => r !== currentRoute);
</script>

<div class="{styles.breadcrumbs} {$$restProps.class}">
  <span class={styles.item}>src</span>

  <IconChevronRight class={styles.separator} />

  <Popup bind:open={isMenuOpened}>
    <button
      slot="button"
      class="{styles.item} {styles.active}"
      on:click={() => (isMenuOpened = true)}
    >
      <svelte:component this={routeIcon} class={styles.icon} />
      {currentRoute.label}
    </button>

    <div class={styles.list}>
      {#each restRoutes as { to, label, icon = IconJson } (to)}
        <Link
          class="{styles.item} {styles.link}"
          {to}
          on:click={() => (isMenuOpened = false)}
        >
          <svelte:component this={icon} class={styles.icon} />
          {label}
        </Link>
      {/each}
    </div>
  </Popup>
</div>

// src/routes/IndexRoute/Breadcrumbs/Breadcrumbs.tsx
import { Breadcrumbs as MuiBreadcrumbs, Typography } from '@material-ui/core';
import { NavigateNext } from '@material-ui/icons';
import React from 'react';
import { useLocation } from 'react-router-dom';
import cn from 'classnames';

import JsonIcon from '~/assets/icons/json.svg';

import { useStyles } from './Breadcrumbs.styles';
import { routesMeta } from '~/config/routesMeta';

interface BreadcrumbsProps {
  className?: string;
}

export const Breadcrumbs: React.FC<BreadcrumbsProps> = (props) => {
  const classes = useStyles();
  const location = useLocation();
  const route = routesMeta[location.pathname];
  const Icon = route.icon || JsonIcon;

  return (
    <MuiBreadcrumbs
      className={cn(classes.root, props.className)}
      separator={<NavigateNext />}
    >
      <Typography className={classes.item} variant="body1">
        src
      </Typography>
      <Typography className={cn(classes.item, classes.active)} variant="body1">
        <Icon className={classes.icon} />
        {route.label}
      </Typography>
    </MuiBreadcrumbs>
  );
};
