// src/components/GoogleMap/GoogleMap.tsx
import { Skeleton } from "@material-ui/lab";
import React, { useState, useCallback } from "react";
import clsx from "clsx";

import { useCodeBlockContext } from "~/components/CodeLikeBlock";

import { useStyles } from "./GoogleMap.styles";

interface GoogleMapProps {
  className?: string;
  address: string;
  title?: string;
}

const GoogleMapBase: React.FC<GoogleMapProps> = (props) => {
  const context = useCodeBlockContext();
  const classes = useStyles(context);
  const [isLoaded, setLoaded] = useState<boolean>(false);

  const handleLoad = useCallback(() => setLoaded(true), []);

  return (
    <div
      className={clsx(
        classes.googleMap,
        isLoaded && classes.loaded,
        props.className
      )}
    >
      {!isLoaded && (
        <Skeleton className={clsx(classes.block, classes.skeleton)} />
      )}
      <iframe
        className={clsx(classes.block, classes.iframe)}
        title={props.title}
        width="600"
        height="500"
        id="gmap_iframe"
        src={`https://maps.google.com/maps?q=${props.address}&t=&z=13&ie=UTF8&iwloc=&output=embed`}
        frameBorder={0}
        scrolling="no"
        marginHeight={0}
        marginWidth={0}
        onLoad={handleLoad}
      ></iframe>
    </div>
  );
};

export const GoogleMap = React.memo(GoogleMapBase);

// src/components/special/GoogleMap/GoogleMap.svelte
<script lang="ts">
  import { clsx } from 'clsx';

  import Skeleton from '../../common/Skeleton';
  import { getCodeLikeBlockContext } from '../CodeLikeBlock';

  import styles from './GoogleMap.module.scss';

  export let address: string;
  export let title: string = '';

  let isLoaded = false;

  const context = getCodeLikeBlockContext();
</script>

<div
  class={clsx(styles.googleMap, isLoaded && styles.loaded, $$restProps.class)}
  style:--line-height="{$context.lineHeight}px"
>
  {#if !isLoaded}
    <Skeleton class={clsx(styles.block, styles.skeleton)} />
  {/if}
  <iframe
    class={clsx(styles.block, styles.iframe)}
    {title}
    width="600"
    height="500"
    id="gmap_iframe"
    src={`https://maps.google.com/maps?q=${address}&t=&z=13&ie=UTF8&iwloc=&output=embed`}
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
    on:load={() => (isLoaded = true)}
  ></iframe>
</div>
