// src/routes/Contacts/Contacts.svelte
<script lang="ts">
  import LinkOpen from '../../components/common/LinkOpen';
  import CodeLikeBlock, {
    L,
    Kw,
    Sl,
    Fn,
    Br,
  } from '../../components/special/CodeLikeBlock';
  import { IS_HIRABLE } from '../../config/experience';

  import styles from './Contacts.module.scss';
</script>

<CodeLikeBlock>
  <L>
    <Kw>Currently</Kw> I live in <Sl>Kyiv</Sl>, Ukraine.
  </L>
  {#if IS_HIRABLE}
    <L active git="green">
      <Kw>But</Kw> I definitely consider <Fn>remote</Fn> work.
    </L>
  {:else}
    <L git="blue">
      <Kw>I lived</Kw> in <Sl>Israel</Sl> for several years, but decided to return
      back to Ukraine.
    </L>
  {/if}
  <Br />
  <div class={styles.mapWrapper}>
    <L class={styles.map}>
      <!-- <GoogleMap address="Kyiv" title="My Location" /> -->
    </L>

    <div class={styles.contactInfo}>
      <L>
        E-mail:
        <LinkOpen to="mailto:alexdarkmm@gmail.com" external hasLinkIcon={false}>
          alexdarkmm@gmail.com
        </LinkOpen>
      </L>

      <L>
        LinkedIn:
        <LinkOpen to="https://www.linkedin.com/in/alex-zinkevych/" external>
          Alex Zinkevych
        </LinkOpen>
      </L>

      <L>
        GitHub:
        <LinkOpen to="https://github.com/alexeychikk" external>
          alexeychikk
        </LinkOpen>
      </L>

      <Br />

      <!-- <LoveSurvey /> -->
    </div>
  </div>
</CodeLikeBlock>

// src/routes/Contacts/Contacts.tsx
import React from 'react';

import { useStyles } from './Contacts.styles';

import { CodeLikeBlock, Kw, Sl, Br, Fn, L } from '~/components/CodeLikeBlock';
import { GoogleMap } from '~/components/GoogleMap';
import { IfHirable, IfNotHirable } from '~/components/IfHirable';
import { LinkLine } from '~/components/LinkLine';
import { LoveSurvey } from '~/components/LoveSurvey';

export const Contacts: React.FC = () => {
  const classes = useStyles();
  return (
    <CodeLikeBlock>
      <L>
        <Kw>Currently</Kw> I live in <Sl>Kyiv</Sl>, Ukraine.
      </L>
      <IfHirable>
        <L active git="green">
          <Kw>But</Kw> I definitely consider <Fn>remote</Fn> work.
        </L>
      </IfHirable>
      <IfNotHirable>
        <L git="blue">
          <Kw>I lived</Kw> in <Sl>Israel</Sl> for several years, but decided to
          return back to Ukraine.
        </L>
      </IfNotHirable>
      <Br />
      <div className={classes.mapWrapper}>
        <L className={classes.map}>
          <GoogleMap address="Kyiv" title="My Location" />
        </L>

        <div className={classes.contactInfo}>
          <LinkLine label="E-mail" to="mailto:alexdarkmm@gmail.com" external>
            alexdarkmm@gmail.com
          </LinkLine>
          <LinkLine
            label="LinkedIn"
            to="https://www.linkedin.com/in/alex-zinkevych/"
            hasLinkIcon
            external
          >
            Alex Zinkevych
          </LinkLine>
          <LinkLine
            label="GitHub"
            to="https://github.com/alexeychikk"
            hasLinkIcon
            external
          >
            alexeychikk
          </LinkLine>
          <Br />
        </div>
      </div>
      <LoveSurvey />
    </CodeLikeBlock>
  );
};

export default Contacts;
