// src/components/Timeline/TimelineItem.tsx
import { Typography } from "@material-ui/core";
import {
  TimelineItem as MuiTimelineItem,
  TimelineContent,
  TimelineSeparator,
  TimelineDot,
  TimelineConnector,
} from "@material-ui/lab";
import React from "react";
import { format, addMonths } from "date-fns";
import clsx from "clsx";

import { formatIntervalShort } from "~/utils/date";
import { CommentLikeBlock } from "~/components/CommentLikeBlock";

import { useStyles } from "./TimelineItem.styles";

export interface TimelineItemProps {
  children?: React.ReactNode;
  className?: string;
  descriptionTitle?: React.ReactNode;
  dateFrom: Date;
  dateTo?: Date;
  subtitle?: React.ReactNode;
  title: React.ReactNode;
}

const TimelineItemBase: React.FC<TimelineItemProps> = (props) => {
  const classes = useStyles();
  return (
    <MuiTimelineItem className={clsx(classes.timelineItem, props.className)}>
      <TimelineSeparator>
        <TimelineDot color="secondary" variant="outlined" />
        <TimelineConnector className={classes.connector} />
      </TimelineSeparator>

      <TimelineContent className={classes.content}>
        <Typography className={classes.title} variant="h6" color="primary">
          {props.title}
        </Typography>

        <Typography variant="body2">
          {format(props.dateFrom, "MMM yyyy")}
          {" – "}
          {props.dateTo ? format(props.dateTo, "MMM yyyy") : "Present"}
          <span className={classes.timeDiff}>
            {" < "}
            {formatIntervalShort({
              start: props.dateFrom,
              end: addMonths(props.dateTo || new Date(), 1),
            })}
            {" >"}
          </span>
        </Typography>

        {props.subtitle && (
          <Typography className={classes.subtitle} variant="body1">
            {props.subtitle}
          </Typography>
        )}

        {props.children && (
          <CommentLikeBlock
            className={classes.description}
            title={props.descriptionTitle}
          >
            {props.children}
          </CommentLikeBlock>
        )}
      </TimelineContent>
    </MuiTimelineItem>
  );
};

export const TimelineItem = React.memo(TimelineItemBase);

// src/components/special/Timeline/TimelineItem.svelte
<script lang="ts">
  import { clsx } from 'clsx';
  import { addMonths, format } from 'date-fns';

  import { formatIntervalShort } from '../../../utils';

  import styles from './TimelineItem.module.scss';

  export let dateFrom: Date;
  export let dateTo: Date | undefined = undefined;
</script>

<div class={clsx(styles.timelineItem, $$restProps.class)}>
  <h6 class={styles.title}><slot name="title" /></h6>

  <p class={styles.dates}>
    {format(dateFrom, 'MMM yyyy')}
    {' – '}
    {dateTo ? format(dateTo, 'MMM yyyy') : 'Present'}
    <span class={styles.timeDiff}>
      {' < '}
      {formatIntervalShort({
        start: dateFrom,
        end: addMonths(dateTo || new Date(), 1),
      })}
      {' >'}
    </span>
  </p>

  {#if $$slots.subtitle}
    <p class={styles.subtitle}>
      <slot name="subtitle" />
    </p>
  {/if}

  <slot />
</div>
