// src/components/SkillsExplorer/SkillsFolder.tsx
import { Typography } from '@material-ui/core';
import { ExpandMore } from '@material-ui/icons';
import React from 'react';

import FolderIcon from '~/assets/icons/folder-open.svg';

import { SkillItemElement } from './SkillItem';
import { useStyles } from './SkillsFolder.styles';

export type SkillsFolderProps = {
  children:
    | SkillsFolderElement
    | SkillsFolderElement[]
    | SkillItemElement
    | SkillItemElement[];
  name: React.ReactNode;
  icon?: SvgComponent;
  expandable?: boolean;
};

export type SkillsFolderElement = React.ReactElement<SkillsFolderProps>;

export const SkillsFolder: React.FC<SkillsFolderProps> = (props) => {
  const classes = useStyles();
  const Icon = props.icon || FolderIcon;

  return (
    <div className={classes.root}>
      <div className={classes.row}>
        {props.expandable && <ExpandMore className={classes.expandIcon} />}
        <Icon className={classes.icon} />
        <Typography className={classes.name} variant="body1">
          {props.name}
        </Typography>
      </div>
      <div className={classes.childrenWrapper}>{props.children}</div>
    </div>
  );
};

SkillsFolder.defaultProps = {
  expandable: true
};

// src/components/special/SkillsExplorer/SkillsFolder.svelte
<script lang="ts">
  import type { ComponentType } from 'svelte';
  import IconChevronDown from 'svelte-material-icons/ChevronDown.svelte';

  import IconFolderOpen from '../../../assets/icons/folder-open.svg?component';
  import Accordion from '../../common/Accordion/Accordion.svelte';

  import styles from './SkillsFolder.module.scss';

  export let icon: ComponentType = IconFolderOpen;
  export let expandable: boolean = false;

  let expanded: boolean = true;
</script>

<Accordion
  class="{styles.skillsFolder} {expanded ? styles.expanded : ''}"
  bind:expanded
  disabled={!expandable}
>
  <div
    slot="summary"
    class="{styles.summary} {expanded ? styles.expanded : ''}"
  >
    {#if expandable}
      <IconChevronDown class={styles.expandIcon} />
    {/if}
    <svelte:component this={icon} class={styles.icon} />
    <span class={styles.name}><slot name="name" /></span>
    {#if $$slots.hint}
      <span class={styles.hint}><slot name="hint" /></span>
    {/if}
  </div>

  <div slot="details" class={styles.childrenWrapper}>
    <slot />
  </div>
</Accordion>
