// src/components/special/CommentLikeBlock/CommentLikeBlock.svelte
<script lang="ts">
  import { clsx } from 'clsx';

  import styles from './CommentLikeBlock.module.scss';
</script>

<div class={clsx(styles.commentLikeBlock, $$restProps.class)}>
  <div class={styles.slash}>
    /** <slot name="title" />
    {!$$slots.default ? '*/' : ''}
  </div>
  {#if $$slots.default}
    <div class={styles.line} />
    <div class={styles.childrenWrapper}><slot /></div>
    <div class={styles.slash}>&nbsp;*/</div>
  {/if}
</div>

// src/components/CommentLikeBlock/CommentLikeBlock.tsx
import React from "react";
import clsx from "clsx";

import { useStyles } from "./CommentLikeBlock.styles";

interface CommentLikeBlockProps {
  className?: string;
  title?: React.ReactNode;
}

export const CommentLikeBlock: React.FC<CommentLikeBlockProps> = (props) => {
  const classes = useStyles();

  return (
    <div className={clsx(classes.commentLikeBlock, props.className)}>
      <div className={classes.slash}>
        /** {props.title} {!props.children && "*/"}
      </div>
      {props.children && (
        <>
          <div className={classes.line} />
          <div className={classes.childrenWrapper}>{props.children}</div>
          <div className={classes.slash}>&nbsp;*/</div>
        </>
      )}
    </div>
  );
};
