// src/components/NavLink/NavLink.tsx
import React from "react";
import { Link, LinkProps, useRouteMatch } from "react-router-dom";
import clsx from "clsx";

import { ReactComponent as JsonIcon } from "~/assets/icons/json.svg";

import { useStyles } from "./NavLink.styles";

export interface NavLinkProps {
  activeClassName?: string;
  activeOnlyWhenExact?: boolean;
  children: React.ReactNode;
  className?: string;
  hasIcon?: boolean;
  icon?: SvgComponent;
  iconClassName?: string;
  external?: boolean;
  to: string;
  target?: LinkProps["target"];
}

const NavLinkBase: React.FC<NavLinkProps> = (props) => {
  const classes = useStyles();
  const match = useRouteMatch({
    path: props.to,
    exact: props.activeOnlyWhenExact,
  });
  const Icon = props.icon || JsonIcon;
  const Component = props.external ? "a" : Link;

  return (
    // @ts-ignore
    <Component
      className={clsx(
        classes.link,
        match && classes.active,
        match && props.activeClassName,
        props.className
      )}
      target={props.target}
      {...(props.external ? { href: props.to } : { to: props.to })}
    >
      {props.hasIcon && (
        <Icon className={clsx(classes.icon, props.iconClassName)} />
      )}
      {props.children}
    </Component>
  );
};

export const NavLink = React.memo(NavLinkBase);

// src/components/common/NavLink/NavLink.svelte
<script lang="ts">
  import { clsx } from 'clsx';
  import type { ComponentType } from 'svelte';
  import { Link, useLocation } from 'svelte-routing';

  import IconJson from '../../../assets/icons/json.svg?component';

  import styles from './NavLink.module.scss';

  export let activeClass: string = '';
  export let activeOnlyWhenExact: boolean = false;
  export let hasIcon: boolean = false;
  export let icon: ComponentType = IconJson;
  export let external: boolean = false;
  export let to: string;
  export let target: string = '';

  const location = useLocation();
  $: active = activeOnlyWhenExact
    ? $location.pathname === to
    : $location.pathname.startsWith(to);

  $: className = clsx(
    styles.navLink,
    $$restProps.class,
    active && styles.active,
    active && activeClass,
  );
</script>

{#if external}
  <a href={to} {target} class={className}>
    {#if hasIcon}
      <svelte:component this={icon} class={styles.icon} />
    {/if}
    <slot />
  </a>
{:else}
  <Link {to} class={className}>
    {#if hasIcon}
      <svelte:component this={icon} class={styles.icon} />
    {/if}
    <slot />
  </Link>
{/if}
