// src/components/LinkOpen/LinkOpen.tsx
import { Link } from "@material-ui/core";
import { OpenInNew } from "@material-ui/icons";
import React from "react";
import clsx from "clsx";

import { useStyles } from "./LinkOpen.styles";

export interface LinkOpenProps {
  className?: string;
  href: string;
  hasLinkIcon?: boolean;
}

export const LinkOpen: React.FC<LinkOpenProps> = (props) => {
  const classes = useStyles();
  return (
    <Link
      className={clsx(classes.linkOpen, props.className)}
      href={props.href}
      target="_blank"
      rel="external nofollow"
    >
      <span>{props.children}</span>
      {props.hasLinkIcon && <OpenInNew className={classes.icon} />}
    </Link>
  );
};

// src/components/common/LinkOpen/LinkOpen.svelte
<script lang="ts">
  import { clsx } from 'clsx';
  import IconOpenInNew from 'svelte-material-icons/OpenInNew.svelte';
  import { Link } from 'svelte-routing';

  import styles from './LinkOpen.module.scss';

  export let to: string;
  export let external = false;
  export let hasLinkIcon = true;

  let className = clsx(styles.linkOpen, $$restProps.class);
</script>

{#if external}
  <a class={className} href={to} target="_blank" rel="noopener noreferrer">
    <slot />
    {#if hasLinkIcon}
      <IconOpenInNew class={styles.icon} />
    {/if}
  </a>
{:else}
  <Link class={className} {to}>
    <slot />
    {#if hasLinkIcon}
      <IconOpenInNew class={styles.icon} />
    {/if}
  </Link>
{/if}
